# Generated by Django 4.0.8 on 2023-09-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='owner',
            field=models.CharField(default='Superuser', max_length=255),
            preserve_default=False,
        ),
    ]
