# Generated by Django 4.0.8 on 2023-09-21 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_lesson_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonview',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.lesson'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessonview',
            name='status_view',
            field=models.BooleanField(default=False),
        ),
    ]
