# Generated by Django 4.0.8 on 2023-09-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_lessonview_lesson_alter_lessonview_status_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='during_veiw',
            field=models.IntegerField(default=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonview',
            name='viewed_duration',
            field=models.IntegerField(default=0),
        ),
    ]
